//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishOrder
    {
        public int Id { get; set; }
        public Nullable<int> IdDish { get; set; }
        public int IdOrder { get; set; }
        public Nullable<int> IdStCook { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public int Count { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
        public virtual StatusCook StatusCook { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
    }
}
