//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUser { get; set; }
        public string Login { get; set; }
        public string Pussword { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Familia { get; set; }
        public int Role { get; set; }
    
        public virtual Role Role1 { get; set; }
    }
}
